-- Migration: add laboratorio_id (FK) and password to cliente
-- Purpose: support client self-registration at /registro-cliente
-- The cliente table was missing the `laboratorio_id` foreign key that links a
-- client to the laboratory, and the `password` column used by the registration
-- form (mirrors the empleados.contraseña pattern used by /iniciar-sesion).

-- 1) Link each client to the laboratory that owns it.
--    Referenced column: laboratorio.id (uuid, generated by gen_random_uuid()).
--    ON DELETE SET NULL keeps clients around if a laboratory is ever removed.
--    Nullable so existing cliente rows are unaffected.
ALTER TABLE "public"."cliente"
  ADD COLUMN IF NOT EXISTS "laboratorio_id" uuid
    REFERENCES "public"."laboratorio" ("id")
    ON DELETE SET NULL;

-- 2) Store the password provided during self-registration.
--    Nullable for existing rows; new registrations always provide a value.
--    NOTE: this matches the existing plaintext-column approach of empleados.contraseña.
--    When migrating to Supabase Auth, switch registration/login to supabase.auth
--    signUp / signInWithPassword and drop this column.
ALTER TABLE "public"."cliente"
  ADD COLUMN IF NOT EXISTS "password" text;
